version: '2.3'

networks:
  dc01:
  dc02:

volumes:
  dc01-zookeeper-data-01:
    driver: local
  dc01-zookeeper-data-02:
    driver: local
  dc01-zookeeper-data-03:
    driver: local
  dc01-kafka-data-01:
    driver: local
  dc01-kafka-data-02:
    driver: local
  dc01-kafka-data-03:
    driver: local

  dc02-zookeeper-data-01:
    driver: local
  dc02-zookeeper-data-02:
    driver: local
  dc02-zookeeper-data-03:
    driver: local
  dc02-kafka-data-01:
    driver: local
  dc02-kafka-data-02:
    driver: local
  dc02-kafka-data-03:
    driver: local

services:
  
  kafka-manager:
    image: cloudopsengineer/cluster-manager-apache-kafka:2.0.0.2
    container_name: kafka-manager
    environment:
      ZK_HOSTS: dc01-zookeeper01:2181,dc01-zookeeper02:2181,dc01-zookeeper03:2181
      KAFKA_NUMBER_OF_BROKERS: 6
      KAFKA_TOTAL_PARTITIONS_NUMBER: 120
    ports:
      - 8080:8080
    cpus: "1"
    mem_limit: 1024m
    networks:
      dc01:
      dc02:

  mirrormaker:
    image: cloudopsengineer/mirrormaker:2.2.0
    container_name: mirrormaker
    hostname: mirrormaker
    environment:
      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: dc01-kafka01:9092,dc01-kafka02:9092,dc01-kafka03:9092
      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: dc02-kafka01:9092,dc02-kafka02:9092,dc02-kafka03:9092
      NUM_STREAMS: 3
    command:
      - test-mirror
    cpus: "1"
    mem_limit: 1024m
    networks:
      dc01:
      dc02:

  dc01-zookeeper01:
    image: cloudopsengineer/zookeeper:2.2.0
    container_name: dc01-zookeeper01
    hostname: dc01-zookeeper01
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVER_IP_PORT_LIST: dc01-zookeeper01:2888:3888,dc01-zookeeper02:2888:3888,dc01-zookeeper03:2888:3888
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc01-zookeeper-data-01:/data/zookeeper
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc01:

  dc01-zookeeper02:
    image: cloudopsengineer/zookeeper:2.2.0
    container_name: dc01-zookeeper02
    hostname: dc01-zookeeper02
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVER_IP_PORT_LIST: dc01-zookeeper01:2888:3888,dc01-zookeeper02:2888:3888,dc01-zookeeper03:2888:3888
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc01-zookeeper-data-02:/data/zookeeper
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc01:

  dc01-zookeeper03:
    image: cloudopsengineer/zookeeper:2.2.0
    container_name: dc01-zookeeper03
    hostname: dc01-zookeeper03
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVER_IP_PORT_LIST: dc01-zookeeper01:2888:3888,dc01-zookeeper02:2888:3888,dc01-zookeeper03:2888:3888
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc01-zookeeper-data-03:/data/zookeeper
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc01:

  dc01-kafka01:
    image: cloudopsengineer/kafka:2.2.0
    container_name: dc01-kafka01
    hostname: dc01-kafka01
    environment:
      KAFKA_BROKER_ID: 100
      KAFKA_ZOOKEEPER_CONNECT: dc01-zookeeper01:2181,dc01-zookeeper02:2181,dc01-zookeeper03:2181
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc01-kafka-data-01:/data/kafka
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc01:

  dc01-kafka02:
    image: cloudopsengineer/kafka:2.2.0
    container_name: dc01-kafka02
    hostname: dc01-kafka02
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: dc01-zookeeper01:2181,dc01-zookeeper02:2181,dc01-zookeeper03:2181
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc01-kafka-data-02:/data/kafka
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc01:

  dc01-kafka03:
    image: cloudopsengineer/kafka:2.2.0
    container_name: dc01-kafka03
    hostname: dc01-kafka03
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ZOOKEEPER_CONNECT: dc01-zookeeper01:2181,dc01-zookeeper02:2181,dc01-zookeeper03:2181
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc01-kafka-data-03:/data/kafka
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc01:

  dc02-zookeeper01:
    image: cloudopsengineer/zookeeper:2.2.0
    container_name: dc02-zookeeper01
    hostname: dc02-zookeeper01
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVER_IP_PORT_LIST: dc02-zookeeper01:2888:3888,dc02-zookeeper02:2888:3888,dc02-zookeeper03:2888:3888
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc02-zookeeper-data-01:/data/zookeeper
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc02:

  dc02-zookeeper02:
    image: cloudopsengineer/zookeeper:2.2.0
    container_name: dc02-zookeeper02
    hostname: dc02-zookeeper02
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVER_IP_PORT_LIST: dc02-zookeeper01:2888:3888,dc02-zookeeper02:2888:3888,dc02-zookeeper03:2888:3888
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc02-zookeeper-data-02:/data/zookeeper
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc02:

  dc02-zookeeper03:
    image: cloudopsengineer/zookeeper:2.2.0
    container_name: dc02-zookeeper03
    hostname: dc02-zookeeper03
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVER_IP_PORT_LIST: dc02-zookeeper01:2888:3888,dc02-zookeeper02:2888:3888,dc02-zookeeper03:2888:3888
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc02-zookeeper-data-03:/data/zookeeper
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc02:

  dc02-kafka01:
    image: cloudopsengineer/kafka:2.2.0
    container_name: dc02-kafka01
    hostname: dc02-kafka01
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: dc02-zookeeper01:2181,dc02-zookeeper02:2181,dc02-zookeeper03:2181
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc02-kafka-data-01:/data/kafka
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc02:

  dc02-kafka02:
    image: cloudopsengineer/kafka:2.2.0
    container_name: dc02-kafka02
    hostname: dc02-kafka02
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ZOOKEEPER_CONNECT: dc02-zookeeper01:2181,dc02-zookeeper02:2181,dc02-zookeeper03:2181
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc02-kafka-data-02:/data/kafka
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc02:

  dc02-kafka03:
    image: cloudopsengineer/kafka:2.2.0
    container_name: dc02-kafka03
    hostname: dc02-kafka03
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ZOOKEEPER_CONNECT: dc02-zookeeper01:2181,dc02-zookeeper02:2181,dc02-zookeeper03:2181
      KAFKA_HEAP_OPTS: -Xmx2G -Xms1G
    volumes:
      - dc02-kafka-data-03:/data/kafka
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped
    networks:
      dc02:
